JAVAPATH: /home/users/cjyoon/anaconda3/bin/java
PICARDPATH: /home/users/tools/picard/dist/picard.jar
GATKPATH: /home/users/tools/gatk/gatk-3.5/GenomeAnalysisTK.jar
SAMTOOLSPATH: /home/users/cjyoon/anaconda3/bin/samtools
BWAPATH: /home/users/cjyoon/anaconda3/bin/bwa
referencePath: /home/users/data/01_reference/human_g1k_v37/human_g1k_v37.fasta
knownIndelPath: /home/users/data/02_annotation/01_GATK/01_golden_standard/Mills_and_1000G_gold_standard.indels.b37.vcf
dbSnpPath: /home/users/data/02_annotation/01_GATK/02_db_snp/dbsnp_138.b37.vcf
